name: 🐞 Bug Report
description: A generic bug report
title: "[BUG]: "
labels: ["Type: 🐞 bug", "Status: 🖐 available"]
assignees:
  - s1lentq
body:
  - type: markdown
    attributes:
      value: 💖 Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: 👉👈 Contact Details (optional)
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: 🤔 What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: A bug happened!
    validations:
      required: true
  - type: textarea
    id: metainfo
    attributes:
      label: ⚠️ Meta-information
      description: | 
        ➡️ What version of engine are you seeing the problem on?
        
        ➡️ Please, paste output from console command below:
        `version; game version; meta version; meta list`
         
        ➡️ (Optional) You could also provide info about AMX Mod X (version below `1.9.0` are *not* supported!):
        `amxx version; amxx plugins`
        
        ➡️ Your environment: OS ( 🪟 `Windows` or 🐧 `Linux`), OS Vetsion, etc.
      render: shell
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: 📄 Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: markdown
    attributes:
      value: Thanks for completing our form!
