name: Bug Report
description: A generic bug report
title: "[BUG]: "
labels: ["Type: Bug", "Status: Available"]
assignees:
  - s1lentq
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details (optional)
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: A bug happened!
    validations:
      required: true
  - type: dropdown
    id: mmrversion
    attributes:
      label: Metamod-r Version
      description: What version of Metamod-r are you running?
      options:
        - 1.3.0.138 (Default)
        - 1.3.0.131
        - 1.3.0.128
        - 1.3.0.126
        - 1.3.0.125
        - 1.3.0.119
        - 1.3.0.107
        - 1.3.0.86
        - 1.3.0.85
        - 1.3.0.84
      default: 0
    validations:
      required: true
  - type: dropdown
    id: amxxversion
    attributes:
      label: AMX Mod X Version
      description: What version of AMX Mod X are you running?
      options:
        - 1.8.2 (Default)
        - 1.9.x
        - 1.10.x
        - I am not use AMX Mod X
      default: 0
    validations:
      required: true
  - type: dropdown
    id: engine
    attributes:
      label: What engine are you seeing the problem on?
      multiple: true
      options:
        - HLDS
        - reHLDS
    validations:
      required: true
  - type: dropdown
    id: enginever
    attributes:
      label: What version of engine are you seeing the problem on?
      multiple: true
      options:
        - HLDS (5758) Windows
        - HLDS (5787) Linux
        - HLDS (6132) Both
        - HLDS (6153) Both
        - HLDS (6153b) Both
        - HLDS (7561) Windows
        - HLDS (7559) Linux
        - HLDS (7882) Linux
        - HLDS (8308) Both
        - HLDS (8196) Linux
        - HLDS (8684) Both
        - reHLDS (Nightly CI build)
        - reHLDS (3.13.0.788)
        - reHLDS (3.12.0.780)
        - reHLDS (3.11.0.779)
        - reHLDS (3.11.0.777)
        - reHLDS (3.11.0.776)
        - reHLDS (3.11.0.767)
        - reHLDS (3.10.0.761)
        - reHLDS (3.10.0.760)
        - reHLDS (3.10.0.760-dev)
        - reHLDS (3.10.0.759)
        - reHLDS (3.9.0.752)
        - reHLDS (3.8.0.739)
        - reHLDS (3.8.0.723)
        - reHLDS (3.8.0.715)
        - reHLDS (3.8.0.711)
        - reHLDS (3.8.0.702)
        - reHLDS (3.7.0.698)
        - reHLDS (3.7.0.697)
        - reHLDS (3.7.0.696)
        - reHLDS (3.7.0.695)
        - reHLDS (3.7.0.694)
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: What OS are you seeing the problem on?
      multiple: true
      options:
        - Windows
        - Linux
    validations:
      required: true
  - type: dropdown
    id: osver
    attributes:
      label: What OS version are you seeing the problem on?
      multiple: true
      options:
        - Windows 7
        - Windows 8
        - Windows 8.1
        - Windows 10
        - Windows 11
        - Ubuntu 14.x
        - Ubuntu 16.x
        - Ubuntu 18.x
        - Ubuntu 20.x
        - Ubuntu 22.x
        - Debian 10
        - Debian 11
        - Debian 12
        - Other Linux
    validations:
      required: true 
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: markdown
    attributes:
      value: Thanks for completing our form!