name: Bug Report
description: A generic bug report
title: "[BUG]: "
labels: ["Type: 🐞 bug", "Status: 🖐 available"]
assignees:
  - s1lentq
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details (optional)
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: A bug happened!
    validations:
      required: true
  - type: dropdown
    id: engine
    attributes:
      label: What engine are you seeing the problem on?
      multiple: true
      options:
        - HLDS
        - reHLDS
    validations:
      required: true
  - type: dropdown
    id: enginever
    attributes:
      label: What version of engine are you seeing the problem on?
      multiple: true
      options:
        - HLDS (5758) Windows
        - HLDS (5787) Linux
        - HLDS (6132) Both
        - HLDS (6153) Both
        - HLDS (6153b) Both
        - HLDS (7561) Windows
        - HLDS (7559) Linux
        - HLDS (7882) Linux
        - HLDS (8308) Both
        - HLDS (8196) Linux
        - HLDS (8684) Both
        - reHLDS (Nightly CI build, I will provide version or commit)
        - reHLDS (3.13.0.788)
        - reHLDS (3.12.0.780)
        - reHLDS (3.11.0.779)
        - reHLDS (3.11.0.777)
        - reHLDS (3.11.0.776)
        - reHLDS (3.11.0.767)
        - reHLDS (3.10.0.761)
        - reHLDS (3.10.0.760)
        - reHLDS (3.10.0.759)
        - reHLDS (3.9.0.752)
        - reHLDS (3.8.0.739)
        - reHLDS (3.8.0.723)
        - reHLDS (3.8.0.715)
        - reHLDS (3.8.0.711)
        - reHLDS (3.8.0.702)
        - reHLDS (3.7.0.698)
        - reHLDS (3.7.0.697)
        - reHLDS (3.7.0.696)
        - reHLDS (3.7.0.695)
        - reHLDS (3.7.0.694)
    validations:
      required: true
  - type: dropdown
    id: regamedllcsversion
    attributes:
      label: ReGameDLL_CS Version
      multiple: true
      options:
        - I am not use ReGameDLL_CS
        - Custom version from CI (I will provide version or commit)
        - 5.26.0.668
        - 5.22.0.593
        - 5.21.0.593
        - 5.21.0.576
        - 5.21.0.575
        - 5.21.0.547
        - 5.21.0.556
        - 5.21.0.546
        - 5.21.0.540
        - 5.21.0.534
        - 5.20.0.525
        - 5.20.0.516
        - 5.20.0.505
        - 5.20.0.498
        - 5.20.0.496
        - 5.20.0.492
        - 5.19.0.486
        - 5.19.0.485
        - 5.19.0.484
        - 5.18.0.482
        - 5.18.0.481
        - 5.18.0.480
        - 5.18.0.479
        - 5.18.0.475
        - 5.18.0.474
        - 5.18.0.473
        - 5.18.0.472
        - 5.18.0.470
        - 5.18.0.469
        - 5.18.0.467
        - 5.18.0.468
        - 5.17.0.466
        - 5.16.0.465
        - 5.16.0.460
        - 5.15.0.459
        - 5.15.0.457
      default: 0
    validations:
      required: true
  - type: dropdown
    id: reapiversion
    attributes:
      label: ReAPI Version
      description: What version of ReAPI are you running?
      options:
        - I am not use ReAPI
        - Custom version from CI (I will provide version or commit)
        - 5.24.0.300
        - 5.22.0.253
        - 5.22.0.254
        - 5.21.0.252
        - 5.21.0.248
        - 5.20.0.236
        - 5.20.0.231
        - 5.19.0.217
        - 5.19.0.211
        - 5.19.0.210
        - 5.18.0.205
        - 5.18.0.203
        - 5.18.0.202
        - 5.17.0.200
        - 5.15.0.197
        - 5.16.0.198
        - 5.14.0.195
        - 5.13.0.194
        - 5.12.0.192
        - 5.11.0.191
        - 5.11.0.190
        - 5.11.0.189
        - 5.10.0.188
        - 5.10.0.187
        - 5.10.0.186
        - 5.9.0.178
        - 5.9.0.177
        - 5.9.0.171
        - 5.9.0.172
        - 5.9.0.167
        - 5.8.0.166
        - 5.8.0.165
        - 5.8.0.163
        - 5.7.0.162
        - 5.6.0.161
        - 5.6.0.160
        - 5.6.0.158
        - 5.6.0.157
        - 5.6.0.156
        - 5.6.0.155
        - 5.5.0.150
        - 5.5.0.148
        - 5.2.0.145
        - 5.2.0.143
        - 5.2.0.142
      default: 0
    validations:
      required: true
  - type: dropdown
    id: metamodrversion
    attributes:
      label: Metamod-r Version
      description: What version of Metamod-r are you running?
      options:
        - I am not use Metamod-R
        - Custom version from CI (I will provide version or commit)
        - 1.3.0.138
        - 1.3.0.131
        - 1.3.0.128
        - 1.3.0.126
        - 1.3.0.125
        - 1.3.0.119
        - 1.3.0.107
        - 1.3.0.86
        - 1.3.0.85
        - 1.3.0.84
      default: 0
    validations:
      required: true
  - type: dropdown
    id: reunionrversion
    attributes:
      label: ReUnion Version
      description: What version of ReUnion are you running?
      options:
        - I am not use reUnion
        - 0.2.0.13
        - 0.2.0.6
        - 0.1.0.92d
        - 0.1.0.92c
        - 0.1.0.92
        - 0.1.0.89
        - 0.1.75.0 (beta)
        - 0.1.0.137 (beta)
        - 0.1.0.135 (beta)
        - 0.1.0.133 (beta)
        - 0.1.0.130 (beta)
        - 0.1.0.129 (beta)
        - 0.1.0.127 (beta)
        - 0.1.0.125 (beta)
        - 0.1.0.123 (beta)
        - 0.1.0.113 (beta)
        - 0.1.0.112 (beta)
      default: 0
    validations:
      required: true
  - type: dropdown
    id: amxxversion
    attributes:
      label: AMX Mod X Version
      description: What version of AMX Mod X are you running?
      options:
        - I am not use AMX Mod X
        - 1.8.2
        - 1.9.x
        - 1.10.x
        - reAmxX (deprecated and outdated)
      default: 0
    validations:
      required: true
  - type: dropdown
    id: resemiclipversion
    attributes:
      label: ReSemiclip Version
      description: What version of ReSemiclip are you running?
      options:
        - I am not use ReSemiclip
        - 2.4.3
        - 2.3.9
        - 2.3.8
      default: 0
    validations:
      required: true
  - type: dropdown
    id: recheckerversion
    attributes:
      label: ReChecker Version
      description: What version of ReChecker are you running?
      options:
        - "I am not use ReChecker"
        - "2.7"
        - "2.4"
        - "2.5"
        - "2.3"
      default: 0
    validations:
      required: true
  - type: dropdown
    id: revoiceversion
    attributes:
      label: ReVoice Version
      description: What version of ReVoice are you running?
      options:
        - "I am not use ReVoice"
        - 0.1.0.34
        - 0.1.0.33
        - 0.1.0.32
        - 0.1.0.31
        - 0.1.0.30
        - 0.1.0.29
        - 0.1.0.26
      default: 0
    validations:
      required: true
  - type: dropdown
    id: refreelookeversion
    attributes:
      label: ReFreeLook Version
      description: What version of ReFreeLook are you running?
      options:
        - "I am not use ReFreeLook"
        - 0.1.8
        - 0.1.7
        - 0.1.6
      default: 0
    validations:
      required: true
  - type: dropdown
    id: relocalizebugfixversion
    attributes:
      label: ReLocalizeBugFix Version
      description: What version of ReLocalizeBugFix are you running?
      options:
        - "I am not use ReLocalizeBugFix"
        - "2.8"
      default: 0
    validations:
      required: true
  - type: dropdown
    id: hitboxtrackerversion
    attributes:
      label: hitboxtracker Version
      description: What version of hitboxtracker are you running?
      options:
        - "I am not use hitboxtracker"
        - "1.1"
        - "1.0"
      default: 0
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: What OS are you seeing the problem on?
      multiple: true
      options:
        - Windows
        - Linux
    validations:
      required: true
  - type: dropdown
    id: osver
    attributes:
      label: What OS version are you seeing the problem on?
      multiple: true
      options:
        - Windows 7
        - Windows 8
        - Windows 8.1
        - Windows 10
        - Windows 11
        - Ubuntu 14.x
        - Ubuntu 16.x
        - Ubuntu 18.x
        - Ubuntu 20.x
        - Ubuntu 22.x
        - Debian 10
        - Debian 11
        - Debian 12
        - Other Linux
    validations:
      required: true 
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: markdown
    attributes:
      value: Thanks for completing our form!