name: Sync labels

on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'Repository'
        required: true
        type: choice
        options:
          - rehlds/.github
          - rehlds/rehlds.github.io
          - rehlds/ReHLDS
          - rehlds/ReGameDLL_CS
          - rehlds/ReAPI
          - rehlds/Metamod-R
          - rehlds/ReVoice
          - rehlds/ReUnion
          - rehlds/ReSemiclip
          - rehlds/ReFreeLook
          - rehlds/ReChecker
          # Archieved
          - rehlds/relocalizebugfix
          - rehlds/reamxmodx
          - rehlds/hitboxtracker
          - rehlds/metamod-r.org

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: micnncim/action-label-syncer@v1
        with:
          manifest: .github/labels.yml
          repository: |
            ${{ inputs.repo }}

          token: ${{ secrets.REHLDS_LABELS_PAT }}
